// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyB0lvSrxJTrJ9oblDXsAiKMcgx2CoiAjqI',
  //   appId: '1:232162551448:web:4689ae373d07ffc6c852ed',
  //   messagingSenderId: '232162551448',
  //   projectId: 'home-quest-88855',
  //   authDomain: 'home-quest-88855.firebaseapp.com',
  //   storageBucket: 'home-quest-88855.appspot.com',
  //   measurementId: 'G-LVGVD660FD',
  // );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB0lvSrxJTrJ9oblDXsAiKMcgx2CoiAjqI",
      authDomain: "home-quest-88855.firebaseapp.com",
      projectId: "home-quest-88855",
      storageBucket: "home-quest-88855.appspot.com",
      messagingSenderId: "232162551448",
      appId: "1:232162551448:web:c4782b181576589ec852ed",
      measurementId: "G-8RVLDS4SRW");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_cgeeUeT74ImCnVsgdRF2K6Rx7npRZMk',
    appId: '1:232162551448:android:6a16e6d76fb4a1cac852ed',
    messagingSenderId: '232162551448',
    projectId: 'home-quest-88855',
    storageBucket: 'home-quest-88855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_3BgK6VZU7xzF3ly9UryPT-7kRmEong',
    appId: '1:232162551448:ios:ea8732c620596b52c852ed',
    messagingSenderId: '232162551448',
    projectId: 'home-quest-88855',
    storageBucket: 'home-quest-88855.appspot.com',
    iosBundleId: 'com.example.realEstateApp',
  );
}
